import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import techbar from "@/public/Tech Bar (4).svg";
import { Toaster } from "sonner";
import { Playfair } from "next/font/google";
import { LanguageProvider } from "./context/languageContext";
// import SmoothScroll from "@/components/global/smoothScroll";
export const poppins = Poppins({
  variable: "--font-arimo",
  subsets: ["latin"],
  weight: ["400"],
});

// export const playfair=Playfair({variable:'--font-playfair',subsets:["latin"],weight:["400"]})
// const sans = Open_Sans({
//   variable: "--font-sans",
//   subsets: ["latin"],
//   weight: ["400", "700"],
// });
export const metadata: Metadata = {
  title: "TechBar",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // favicon from public folder
    shortcut: "/Tech Bar (4).svg",
    apple: "/Tech Bar (4).svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${poppins.className}`}>
        <LanguageProvider>
          {/* <ThemeProvider
          attribute="class"
          defaultTheme="light"
          
          disableTransitionOnChange
        > */}
          <Toaster position="bottom-right" />
          <Navbar />
          <main className="min-h-screen">{children}</main>
          <Footer />
          {/* </ThemeProvider> */}
        </LanguageProvider>
      </body>
    </html>
  );
}
