import type { Metadata } from "next";
import "./globals.css";

import { Lato, Outfit, Sansita_Swashed, Open_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const sans = Open_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${sans.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* NAVBAR ALWAYS ON TOP */}
          <Navbar />

          {/* MAIN CONTENT */}
          <main className="min-h-screen">
            {children}
          </main>

          {/* FOOTER ALWAYS AT BOTTOM */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
